# tracking db config.

table_primary_keys:
  - TABLE_SCHEMA
  - TABLE_NAME

diff_table:
  TABLE_SCHEMA: 1
  TABLE_NAME: 1
  ENGINE: 1
  TABLE_ROWS: 0
  TABLE_COLLATION: 1
  TABLE_COMMENT: 1
  create_ddl: 0

column_primary_keys:
  - TABLE_SCHEMA
  - TABLE_NAME
  - COLUMN_NAME

diff_column:
  TABLE_SCHEMA: 1
  TABLE_NAME: 1
  COLUMN_NAME: 1
  ORDINAL_POSITION: 0
  COLUMN_DEFAULT: 1
  IS_NULLABLE: 1
  DATA_TYPE: 1
  CHARACTER_MAXIMUM_LENGTH: 1
  CHARACTER_OCTET_LENGTH: 1
  NUMERIC_PRECISION: 1
  NUMERIC_SCALE: 1
  DATETIME_PRECISION: 1
  CHARACTER_SET_NAME: 1
  COLLATION_NAME: 1
  COLUMN_TYPE: 1
  COLUMN_KEY: 1
  EXTRA: 1
  COLUMN_COMMENT: 1
