# tracking db config.

-
  host: 192.168.0.100
  port: 3306
  db: test1
  user: root
  passwd: root
  charset: utf8
-
  host: 192.168.0.100
  port: 3306
  db: test2
  user: root
  passwd: root
  charset: utf8

